version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "python-dev"
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - db-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "bbereoff@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "16543:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - db-network

networks:
  db-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin-data:
