# Generated by Django 4.1 on 2022-08-21 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census_etl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusetl',
            name='capital_gain',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusetl',
            name='capital_loss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusetl',
            name='class_category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='censusetl',
            name='education_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusetl',
            name='eduction',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='censusetl',
            name='fnlwgt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusetl',
            name='hours_per_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='censusetl',
            name='marital_status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='censusetl',
            name='native_country',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='censusetl',
            name='occupation',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='censusetl',
            name='race',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='censusetl',
            name='relationship',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='censusetl',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
