# Generated by Django 4.1 on 2022-08-22 01:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('census_etl', '0003_rename_eduction_censusetl_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('counter', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
