# Generated by Django 4.0.2 on 2022-08-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census_etl', '0004_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusetl',
            name='line',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
