# Generated by Django 4.0.2 on 2022-08-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census_etl', '0005_censusetl_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='censusetl',
            name='line',
        ),
    ]
