from enum import Enum


class NativeCountryEnum(Enum):
   UNITED_STATES = "United-States"
   CAMBODIA = "Cambodia"
   ENGLAND = "England"
   PUERTO_RICO = "Puerto-Rico"
   CANADA = "Canada"
   GERMANY = "Germany"
   OUTLYING_US = "Outlying-US(Guam-USVI-etc)"
   INDIA = "India"
   JAPAN = "Japan"
   GREECE = "Greece"
   SOUTH = "South"
   CHINA = "China"
   CUBA = "Cuba"
   IRAN = "Iran"
   HONDURAS = "Honduras"
   PHILIPPINES = "Philippines"
   ITALY = "Italy"
   POLAND = "Poland"
   JAMAICA = "Jamaica"
   VIETNAM = "Vietnam"
   MEXICO = "Mexico"
   PORTUGAL = "Portugal"
   IRELAND = "Ireland"
   FRANCE = "France"
   DOMINICAN_REPUBLIC = "Dominican-Republic"
   LAOS = "Laos"
   ECUADOR = "Ecuador"
   TAIWAN = "Taiwan"
   HAITI = "Haiti"
   COLUMBIA = "Columbia"
   HUNGARY = "Hungary"
   GUATEMALA = "Guatemala"
   NICARAGUA = "Nicaragua"
   SCOTLAND = "Scotland"
   THAILAND = "Thailand"
   YUGOSLAVIA = "Yugoslavia"
   EL_SALVADOR = "El-Salvador"
   TRINADAD_TOBAGO = "Trinadad&Tobago"
   PERU = "Peru"
   HONG = "Hong"
   HOLAND_NETHERLANDS = "Holand-Netherlands"
   EMPTY_VALUE = "?"